### ISSUE TITLE
Mislabeling in CANDELS tree?

### ISSUE THREAD

**Issue by willettk** [CKrawczyk/retirement_limit_estimator#1]
Why does the task numbering jump from 0 to 2 here?

https://github.com/CKrawczyk/retirement_limit_estimator/blob/master/retirement_based_on_tree.py#L11

**Comment by CKrawczyk** [comment]
That was a typo when I first typed it in (forgot a number), but the array is self consistent.  The numbers are just labels, the order does not matter much.

As a side note, that file was part of a hack day project and is not the nicest code in the world.  If I were to redo that code I would use a dictionary format similar to the `expected_information.py` code.

**Comment by CKrawczyk** [comment]
Closed by https://github.com/CKrawczyk/retirement_limit_estimator/pull/2
